
services:
  # 1) MinIO (Object Store)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    volumes:
      - minio-data:/data
      - minio-config:/root/.minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      retries: 3

  # 2) PostgreSQL (Metadata Store)
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  # 3) lakeFS Server
  lakefs:
    image: treeverse/lakefs:latest
    container_name: lakefs
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - LAKEFS_DATABASE_TYPE=postgres
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=${LAKEFS_ENCRYPT_SECRET_KEY}
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://minio:9000
      - LAKEFS_BLOCKSTORE_S3_DISCOVER_BUCKET_REGION=false
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./lakectl.yaml:/home/lakefs/.lakectl.yaml:ro
      - lakefs-data:/data         # dữ liệu nội bộ lakeFS
      - ./data:/upload            # upload từ máy host vào lakeFS
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/v1/health"]
      interval: 15s
      retries: 5

  # 4) MinIO client (mc) – để upload file dễ dàng
  mc:
    image: minio/mc:latest
    container_name: mc
    entrypoint: ["tail", "-f", "/dev/null"]
    environment:
      - MC_HOST_minio=http://admin:${MINIO_ROOT_PASSWORD}@minio:9000
    volumes:
      - ./data:/data              # cho phép truy cập file upload

volumes:
  minio-data:
  minio-config:
  postgres-data:
  lakefs-data:
